andy_diffuse_river_homepage:
    path:     /
    defaults: { _controller: AndyDiffuseRiverBundle:Index:index }

andy_diffuse_river_parameter:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/parameter.yml"
    prefix:   /parameter

andy_diffuse_river_project:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/project.yml"
    prefix:   /project

andy_diffuse_river_point:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/point.yml"
    prefix:   /project

andy_diffuse_river_parameter_value:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/parameter_value.yml"
    prefix:   /project

andy_diffuse_river_calculate:
    path:     /calculate
    defaults: { _controller: AndyDiffuseRiverBundle:Calculate:index }

andy_diffuse_river_about:
    path:     /about
    defaults: { _controller: AndyDiffuseRiverBundle:About:about }
