andy_diffuse_river_project:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/project.yml"
    prefix:   /project

andy_diffuse_river_point:
    resource: "@AndyDiffuseRiverBundle/Resources/config/routing/point.yml"
    prefix:   /project

andy_diffuse_river_homepage:
    path:     /
    defaults: { _controller: AndyDiffuseRiverBundle:Index:index }
