parameter_value_show:
    path:     /{project}/point/{id}/param/{parameter}/
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:show" }
    methods:  [GET, POST]

parameter_value_edit:
    path:     /{project}/point/{id}/param_value/{param_value}/edit
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:edit" }
    methods:  [GET, POST]

parameter_value_new:
    path:     /{project}/point/{id}/param_value/{param_value}/new
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:new" }
    methods:  [GET, POST]

parameter_value_delete:
    path:     /{project}/point/{id}/param_value/{param_value}/delete
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:delete" }
    methods:  [GET, DELETE]

parameter_value_delete_all:
    path:     /{project}/point/{id}/param/{parameter}/delete_all
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:deleteAll" }
    methods:  [GET, DELETE]

parameter_value_result_delete:
    path:     /{project}/point/{id}/param/{parameter}/result/{result}/delete
    defaults: { _controller: "AndyDiffuseRiverBundle:ParameterValue:deleteResult" }
    methods:  [GET, DELETE]
