parameter_index:
    path:     /
    defaults: { _controller: "AndyDiffuseRiverBundle:Parameter:index" }
    methods:  GET

parameter_new:
    path:     /new
    defaults: { _controller: "AndyDiffuseRiverBundle:Parameter:new" }
    methods:  [GET, POST]

parameter_edit:
    path:     /{id}/edit
    defaults: { _controller: "AndyDiffuseRiverBundle:Parameter:edit" }
    methods:  [GET, POST]

parameter_delete:
    path:     /{id}/delete
    defaults: { _controller: "AndyDiffuseRiverBundle:Parameter:delete" }
    methods:  [GET, DELETE]

parameter_delete_all:
    path:     /delete_all
    defaults: { _controller: "AndyDiffuseRiverBundle:Parameter:delete_all" }
    methods:  [GET]
