project_show:
    path:     /{id}/show
    defaults: { _controller: "AndyDiffuseRiverBundle:Project:show" }
    methods:  GET

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "AndyDiffuseRiverBundle:Project:edit" }
    methods:  [GET, POST]

project_delete:
    path:     /{id}/delete
    defaults: { _controller: "AndyDiffuseRiverBundle:Project:delete" }
    methods:  DELETE
