<?php

namespace Andy\DiffuseRiverBundle\Repository;

/**
 * ParamDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamDateRepository extends \Doctrine\ORM\EntityRepository
{
}
