<?php

namespace Andy\DiffuseRiverBundle\Repository;

/**
 * ParamValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamValueRepository extends \Doctrine\ORM\EntityRepository
{
}
